### ISSUE TITLE
[Question] Wondering about the usage of constant definition with `companion object` and top-level

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nyinyihtunlwin-codigo/nimble-survey#12]
Could you please clarify why there are two different ways to define constants inside `EncryptedSharedPreferences`? What are the main pros and cons of each approach?

https://github.com/nyinyihtunlwin-codigo/nimble-survey/blob/3a42ba4f267e0221fbfd3ec0d381c9887c4054e7/core/datastore/src/main/java/com/nyinyihtunlwin/datastore/EncryptedSharedPreferences.kt#L11-L20

**Comment by nyinyihtunlwin-codigo** [comment]
### Top-level Constants:

The line `private const val APP_KEY_PREFS = "app_key_prefs"` is designed to create a constant that's only needed within the file. This makes it easy to access without referencing a specific class, which is helpful for details specific to how the code is implemented.

**Pros**: It simplifies accessing constants that are only needed within the file's implementation.

**Cons**: Since it's private, it can't be accessed from other files, limiting its use to the file where it's declared. This could lead to confusion if other files define similar constants.

### Companion Object Constants:

Companion object constants are used to group constants related to a specific class. This improves organization and readability. These constants can be accessed from outside the class using the class name, providing a clear scope and context.

**Pros**:  It groups related constants together, making code organization better. Also, it's accessible from outside the class using the class name, which gives a clear context.

**Cons**: To access them, you need to reference the class, which can be less convenient for constants used in multiple classes.
