### ISSUE TITLE
[Feature] Apply library to parse JSON:API

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nyinyihtunlwin-codigo/nimble-survey#14]
Our provided API follows the [JSON:API](https://jsonapi.org/) specification, and your current API models seem a bit manual to parse the response.
It would be great if you could propose and apply a mechanism or library that can parse the response models automatically in a much simpler way ⛏️

**Comment by nyinyihtunlwin-codigo** [comment]
Hi @hoangnguyen92dn , for the json parsing, I used [kotlinx.serialization Converter](https://github.com/square/retrofit/tree/trunk/retrofit-converters/kotlinx-serialization) with Retrofit, which is highly effective and seamless. However, if you're looking for alternatives, Moshi and Gson are also excellent choices. 
May I know the exact place you want me to polish?

**Comment by hoangnguyen92dn** [comment]
@nyinyihtunlwin-codigo It's up to you; you could go with the library you're familiar with. The main idea is to reduce unnecessary attributes in the JSON specification 💡

**Comment by nyinyihtunlwin-codigo** [comment]
@hoangnguyen92dn , I see. I will use [Nimble's JSON API library](https://github.com/nimblehq/jsonapi-kotlin) to make it happen. Thanks.

**Comment by nyinyihtunlwin-codigo** [comment]
For automatic json parsing, I used [Nimble's JSON API](https://github.com/nimblehq/jsonapi-kotlin) with custom created json converter factory named ([NbJsonConverterFactory](https://github.com/nyinyihtunlwin-codigo/nimble-survey/blob/fix/issue_5_json_parser/core/network/src/main/java/com/nyinyihtunlwin/network/NbJsonConverterFactory.kt)). 

In order to follow these changes, additional GitHub information will be needed to add in `key.properties` file.
(Updated in [README.md](https://github.com/nyinyihtunlwin-codigo/nimble-survey/blob/main/README.md) as well).

I've updated my code and merged in this [pull request](https://github.com/nyinyihtunlwin-codigo/nimble-survey/pull/19).
Please kindly check and let me know if anything needed. Thanks.
